# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fib_even_sum(n)
    f = [1, 2];
        for i in 3:n
        push!(f, 0)
        f[i] = f[i-2] + f[i-1]
        end
    sum(filter(iseven, f))
end

fib_even_sum(32)